[package]
name = "pbscript-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.24", features = ["color", "derive"] }
hashbrown = "0.15.1"
pbscript-lib = { path = "../lib/" }

[[bin]]
name = "pbscript"
path = "src/main.rs"
