#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub enum Token<'a> {
    Ident(&'a str),

    Int { slice: &'a str, negative: bool },
    Float { slice: &'a str, negative: bool },
    String(&'a str),
    Boolean(bool),

    Semicolon,
    Colon,
    Comma,
    Period,
    DoublePeriod,
    Equals,
    Bang,
    Question,
    Ampersand,
    AtSign,
    Plus,
    PlusEquals,
    Minus,
    MinusEquals,
    Asterisk,
    AsteriskEquals,
    Slash,
    SlashEquals,
    Lt,
    Gt,
    LtEquals,
    GtEquals,
    DoubleEquals,
    NotEquals,
    DoubleAmpersand,
    DoublePipe,
    Arrow,
    ThickArrow,

    ParenOpen,
    ParenClose,
    BracketOpen,
    BracketClose,
    BraceOpen,
    BraceClose,

    KeywordVar,
    KeywordConst,
    KeywordFn,
    KeywordMatch,
    KeywordIf,
    KeywordElse,
    KeywordWhile,
    KeywordFor,
    KeywordIn,
    KeywordLoop,
    KeywordReturn,
    KeywordBreak,
    KeywordNull, // TODO: remove
    KeywordStruct,
    KeywordEnum,
    KeywordSelf,
}

impl Token<'_> {
    pub fn name(&self) -> &'static str {
        match self {
            Token::Ident(_) => "an identifier",
            Token::Int { .. } => "an integer",
            Token::Float { .. } => "a float",
            Token::String(_) => "a string",
            Token::Boolean(_) => "a boolean",
            Token::Semicolon => "a semicolon",
            Token::Colon => "a colon",
            Token::Comma => "a comma",
            Token::Period => "a period",
            Token::DoublePeriod => "a double period",
            Token::Equals => "an equal sign",
            Token::Bang => "an exclamation point",
            Token::Question => "a question mark",
            Token::Ampersand => "an ampersand",
            Token::AtSign => "an at sign",
            Token::Plus => "a plus sign",
            Token::PlusEquals => "a plus equals sign",
            Token::Minus => "a minus sign",
            Token::MinusEquals => "a minus equals sign",
            Token::Asterisk => "an asterisk",
            Token::AsteriskEquals => "a times equals sign",
            Token::Slash => "a foreward slash",
            Token::SlashEquals => "a slash equals sign",
            Token::Lt => "a less than sign",
            Token::Gt => "a greater than sign",
            Token::LtEquals => "a less than equals sign",
            Token::GtEquals => "a greater than equals sign",
            Token::DoubleEquals => "a double equal sign",
            Token::NotEquals => "an inequal sign",
            Token::DoubleAmpersand => "a double ampersand",
            Token::DoublePipe => "a double pipe",
            Token::Arrow => "an arrow",
            Token::ThickArrow => "a thick arrow",
            Token::ParenOpen => "a open parenthesis",
            Token::ParenClose => "a close parenthesis",
            Token::BracketOpen => "an open square bracket",
            Token::BracketClose => "a close square bracket",
            Token::BraceOpen => "an open curly brace",
            Token::BraceClose => "a close curly brace",
            Token::KeywordVar => "the var keyword",
            Token::KeywordConst => "the const keyword",
            Token::KeywordFn => "the fn keyword",
            Token::KeywordIf => "the if keyword",
            Token::KeywordElse => "the else keyword",
            Token::KeywordMatch => "the match keyword",
            Token::KeywordWhile => "the while keyword",
            Token::KeywordLoop => "the loop keyword",
            Token::KeywordFor => "the for keyword",
            Token::KeywordIn => "the in keyword",
            Token::KeywordReturn => "the return keyword",
            Token::KeywordBreak => "the break keyword",
            Token::KeywordNull => "the null keyword",
            Token::KeywordEnum => "the enum keyword",
            Token::KeywordStruct => "the struct keyword",
            Token::KeywordSelf => "the self keyword",
        }
    }
}
